name: wm-foundry-module-release

on:
  push:
    tags:
      - 'releases/wm-foundry-module/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Github tag
        id: github_tag
        run: echo ::set-output name=GITHUB_TAG::${GITHUB_REF/refs\/tags\/releases\/wm-foundry-module\/v/}

      - name: Release Build
        run: zip -r wm-foundry-module-${{ steps.github_tag.outputs.GITHUB_TAG }}.zip wm-foundry-module/ --exclude \*.iml
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: wm-foundry-module-${{ steps.github_tag.outputs.GITHUB_TAG }}.zip